name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    services:
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: DevOps # Set the target path within your repository

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci
        working-directory: DevOps # Set the working directory to the "DevOps" directory

      - name: Run npm install
        run: npm install
        working-directory: DevOps # Set the working directory to the "DevOps" directory

      - name: Build code
        run: npm run build --if-present
        working-directory: DevOps # Set the working directory to the "DevOps" directory

      - name: Run tests
        run: npm test
        working-directory: DevOps # Set the working directory to the "DevOps" directory
